name: Deploy GitLyte Demo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: ['packages/demo/**', '.github/workflows/deploy-demo.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "demo-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
        
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: 'true'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-demo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-demo-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Astro build
        uses: actions/cache@v4
        with:
          path: |
            packages/demo/.astro
            packages/demo/dist
          key: astro-build-demo-${{ runner.os }}-${{ hashFiles('packages/demo/src/**/*', 'packages/demo/astro.config.mjs', 'packages/demo/package.json') }}
          restore-keys: |
            astro-build-demo-${{ runner.os }}-

      - name: Build Astro demo site
        run: pnpm --filter @gitlyte/demo build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/demo/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4