name: Deploy GitLyte Demo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: ['demo/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "demo-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
        
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: 'true'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-demo-${{ runner.os }}-${{ hashFiles('demo/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-demo-${{ runner.os }}-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: demo/node_modules
          key: node-modules-demo-${{ runner.os }}-${{ hashFiles('demo/pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-demo-${{ runner.os }}-

      - name: Install demo dependencies
        run: pnpm install --frozen-lockfile
        working-directory: demo

      - name: Cache Astro build
        uses: actions/cache@v4
        with:
          path: |
            demo/.astro
            demo/dist
          key: astro-build-demo-${{ runner.os }}-${{ hashFiles('demo/src/**/*', 'demo/astro.config.mjs', 'demo/package.json') }}
          restore-keys: |
            astro-build-demo-${{ runner.os }}-
          
      - name: Build Astro demo site
        run: pnpm run build
        working-directory: demo
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './demo/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4